### PR TITLE
Formatting PR

### LINKED ISSUE #5: Codebase Formatting and Test Suite Proposal
## Codebase Formatting and Test Suite Proposal

Hello @Moealsir @be-great @malazmuzamil98 ,

I recently forked this repository with the intention of contributing and noticed that the codebase lacks consistent formatting. Proper code formatting is crucial for readability and maintainability, especially for open-source projects where multiple contributors are involved.

I propose to implement a code to standardize format, such as **PEP8 + docstring** since we all are familiar with it, to ensure consistent code style across the project. This will help future contributors to read and understand the code more easily.

In addition to this, I noticed that the project does not have a test suite. Having a robust set of tests is important to ensure the stability of the project and prevent regressions when new changes are introduced. **_by integrating the tests into your CI pipeline we can ensure no bug get shipped into package with future PRs._**

I would like to offer my assistance in setting up the code formatter and creating a test suite for the project. This will involve:

1. Setting up the chosen code formatter and formatting the existing codebase which I already started.
2. Writing unit tests for the existing functionality.
3. Setting up a continuous integration service to run these tests automatically on every pull request.

Please let me know if you are interested in this proposal. I am ready to start working on this as soon as I get your approval.

Best Regards,
Younis

### LINKED ISSUE #7: Duplication functions found in `betty_fixer` and `betty_handler` modules.
### Summary:
Duplicate function found in [betty_fixer](https://github.com/Moealsir/betty_fixer/blob/main/bettyfixer/betty_fixer.py) and [betty_handler](https://github.com/Moealsir/betty_fixer/blob/main/bettyfixer/betty_handler.py) modules.

### Description:
While working on a different issue, I noticed that there is a function that is duplicated in both the `betty_fixer` and `betty_handler` modules. Though the interpreter will not raise errors and simply points to the recent object. This could lead to maintenance issues in the future and considered bad code.

### Steps to Reproduce:
1. Open the `betty_fixer` module.
   https://github.com/Moealsir/betty_fixer/blob/d8b52c23cb7f7e8a82b154f90783b45b2a78ec91/bettyfixer/betty_fixer.py#L228-L277
3. Open the `betty_handler` module.
https://github.com/Moealsir/betty_fixer/blob/d8b52c23cb7f7e8a82b154f90783b45b2a78ec91/bettyfixer/betty_handler.py#L4-L42

### Expected Result:
Each function should be unique and not duplicated across different modules.

### Actual Result:
The same function is present in both modules.

### Suggested Fix:
We should refactor the code to remove the duplication. I can't see any differences on either implementations. Simple deletion should suffice.

### LINKED ISSUE #8: PEP8 and Docstring Formatting
#  Document PEP8 and docstring Formatting

## Description

This is an extension of #5 proposal that focuses on migrating formats to PEP8 with pylint and Docstring. To ensure cohesion through contributions.

#### Why Pylint

-  pylint is a more comprehensive tool that checks for a wide range of issues, including coding standards, errors that could lead to bugs in runtime (like type errors), and code smells (like too many branches or lines in a function).
-  It can also check for adherence to a coding standard like PEP 8, but it also includes many other checks that go beyond style.
-  pylint includes features like checking the types of function arguments and return values, checking for unused variables or imports, and checking for cyclic imports.
- It also provides a code rating based on the number and severity of issues found.

#### Objectives

- [x] Adding errors_logs directory
- [x] excluding errors_logs from distribution package
- [x] push code rating to ~9± overall [**_could improve in later PRs_**]
- [x] Skimming off as much error format as possible.
- [x] Add a linting Github action upon [push, pull request]

## Format Analysis

Please be notified these reports are **NOT** comprehensive and merely scratching the surface but are a good place to start 

<details>
<summary> autoprototype Module </summary>

**79 statements analysed.**

Statistics by type
------------------

|type     |number |old number |difference |%documented |%badname |
|---------|-------|-----------|-----------|------------|---------|
|module   |1      |NC         |NC         |0.00        |0.00     |
|class    |0      |NC         |NC         |0           |0        |
|method   |0      |NC         |NC         |0           |0        |
|function |11     |NC         |NC         |0.00        |9.09     |

External dependencies
---------------------
::

    colorama (bettyfixer.autoprototype)

102 lines have been analyzed

Raw metrics
-----------

|type      |number |%     |previous |difference |
|----------|-------|------|---------|-----------|
|code      |82     |80.39 |NC       |NC         |
|docstring |0      |0.00  |NC       |NC         |
|comment   |5      |4.90  |NC       |NC         |
|empty     |15     |14.71 |NC       |NC         |

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |NC       |NC         |
|percent duplicated lines |0.000 |NC       |NC         |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |29     |NC       |NC         |
|refactor   |1      |NC       |NC         |
|warning    |16     |NC       |NC         |
|error      |0      |NC       |NC         |

Messages
--------

| message id                     | occurrences |
|--------------------------------|-------------|
| missing-function-docstring     | 11          |
| bad-indentation                | 11          |
| line-too-long                  | 5           |
| trailing-whitespace            | 4           |
| unused-import                  | 2           |
| unspecified-encoding           | 2           |
| superfluous-parens             | 2           |
| singleton-comparison           | 2           |
| consider-using-f-string        | 2           |
| wrong-import-order             | 1           |
| no-else-return                 | 1           |
| missing-module-docstring       | 1           |
| invalid-name                   | 1           |
| f-string-without-interpolation | 1           |

-----------------------------------
Your code has been rated at 4.18/10
</details>

<details>
<summary> backup.py Module </summary>

**9 statements analysed.**

Statistics by type
------------------

|type     |number |old number |difference |%documented |%badname |
|---------|-------|-----------|-----------|------------|---------|
|module   |1      |NC         |NC         |0.00        |0.00     |
|class    |0      |NC         |NC         |0           |0        |
|method   |0      |NC         |NC         |0           |0        |
|function |1      |NC         |NC         |0.00        |0.00     |

16 lines have been analyzed

Raw metrics
-----------

| type      | number | %     | previous | difference |
|-----------|--------|-------|----------|------------|
| code      | 11     | 68.75 | NC       | NC         |
| docstring | 0      | 0.00  | NC       | NC         |
| comment   | 1      | 6.25  | NC       | NC         |
| empty     | 4      | 25.00 | NC       | NC         |

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |NC       |NC         |
|percent duplicated lines |0.000 |NC       |NC         |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |5      |NC       |NC         |
|refactor   |0      |NC       |NC         |
|warning    |1      |NC       |NC         |
|error      |0      |NC       |NC         |

Messages
--------

| message id                | occurrences |
|---------------------------|-------------|
| trailing-whitespace       | 2           |
| trailing-newlines         | 1           |
| missing-module-docstring  | 1           |
| missing-function-docstring| 1           |
| broad-exception-caught    | 1           |

-----------------------------------
Your code has been rated at 3.33/10
</details>
<details>
<summary> betty_fixer Module </summary>

**210 statements analysed.**

Statistics by type
------------------

|type     |number |old number |difference |%documented |%badname |
|---------|-------|-----------|-----------|------------|---------|
|module   |1      |NC         |NC         |0.00        |0.00     |
|class    |0      |NC         |NC         |0           |0        |
|method   |0      |NC         |NC         |0           |0        |
|function |22     |NC         |NC         |0.00        |4.55     |

**332 lines have been analyzed**

Raw metrics
-----------

|type      |number |%     |previous |difference |
|----------|-------|------|---------|-----------|
|code      |215    |64.76 |NC       |NC         |
|docstring |1      |0.30  |NC       |NC         |
|comment   |50     |15.06 |NC       |NC         |
|empty     |66     |19.88 |NC       |NC         |

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |NC       |NC         |
|percent duplicated lines |0.000 |NC       |NC         |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |34     |NC       |NC         |
|refactor   |4      |NC       |NC         |
|warning    |47     |NC       |NC         |
|error      |0      |NC       |NC         |

Messages
--------

| message id                | occurrences |
|---------------------------|-------------|
| missing-function-docstring| 22          |
| unspecified-encoding      | 21          |
| redefined-outer-name      | 17          |
| wildcard-import           | 4           |
| unused-wildcard-import    | 4           |
| line-too-long             | 4           |
| trailing-whitespace       | 3           |
| consider-using-with       | 2           |
| unused-argument           | 1           |
| too-many-nested-blocks    | 1           |
| too-many-locals           | 1           |
| superfluous-parens        | 1           |
| singleton-comparison      | 1           |
| missing-module-docstring  | 1           |
| missing-final-newline     | 1           |
| invalid-name              | 1           |

-----------------------------------
Your code has been rated at 5.95/10
</details>
<details>
<summary> betty_handler Module </summary>
33 statements analysed.

Statistics by type
------------------

|type     |number |old number |difference |%documented |%badname |
|---------|-------|-----------|-----------|------------|---------|
|module   |1      |NC         |NC         |0.00        |0.00     |
|class    |0      |NC         |NC         |0           |0        |
|method   |0      |NC         |NC         |0           |0        |
|function |4      |NC         |NC         |0.00        |0.00     |

<br>

**61 lines have been analyzed**

**Raw metrics**
-----------

|type      |number |%     |previous |difference |
|----------|-------|------|---------|-----------|
|code      |35     |57.38 |NC       |NC         |
|docstring |0      |0.00  |NC       |NC         |
|comment   |13     |21.31 |NC       |NC         |
|empty     |13     |21.31 |NC       |NC         |

<br>

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |NC       |NC         |
|percent duplicated lines |0.000 |NC       |NC         |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |8      |NC       |NC         |
|refactor   |0      |NC       |NC         |
|warning    |4      |NC       |NC         |
|error      |0      |NC       |NC         |

Messages
--------

|message id                 |occurrences |
|---------------------------|------------|
|unspecified-encoding       |4           |
|missing-function-docstring |4           |
|line-too-long              |3           |
|missing-module-docstring   |1           |

<br>

-----------------------------------
Your code has been rated at 6.36/10

</details>

<details>
<summary> errors_extractor Module </summary>

**21 statements analysed.**

Statistics by type
------------------
 
|type     |number |old number |difference |%documented |%badname |
|---------|-------|-----------|-----------|------------|---------|
|module   |1      |NC         |NC         |0.00        |0.00     |
|class    |0      |NC         |NC         |0           |0        |
|method   |0      |NC         |NC         |0           |0        |
|function |1      |NC         |NC         |0.00        |0.00     |

**39 lines have been analyzed**

Raw metrics
-----------

|type      |number |%     |previous |difference |
|----------|-------|------|---------|-----------|
|code      |23     |58.97 |NC       |NC         |
|docstring |0      |0.00  |NC       |NC         |
|comment   |9      |23.08 |NC       |NC         |
|empty     |7      |17.95 |NC       |NC         |

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |NC       |NC         |
|percent duplicated lines |0.000 |NC       |NC         |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |3      |NC       |NC         |
|refactor   |1      |NC       |NC         |
|warning    |6      |NC       |NC         |
|error      |0      |NC       |NC         |

Messages
--------

|message id                 |occurrences |
|---------------------------|------------|
|unspecified-encoding       |3           |
|redefined-outer-name       |2           |
|unnecessary-pass           |1           |
|missing-module-docstring   |1           |
|missing-function-docstring |1           |
|invalid-name               |1           |
|consider-using-with        |1           |

<br>

-----------------------------------
Your code has been rated at 5.24/10

</details>
<details>
<summary> extract_line </summary>
**522 statements analysed.**

Statistics by type
------------------

| type     | number | old number | difference | %documented | %badname |
|----------|--------|------------|------------|-------------|----------|
| module   | 1      | 1          | =          | 0.00        | 0.00     |
| class    | 0      | NC         | NC         | 0           | 0        |
| method   | 0      | NC         | NC         | 0           | 0        |
| function | 35     | 35         | =          | 0.00        | 0.00     |

**971 lines have been analyzed**

Raw metrics
-----------

|type      |number |%     |previous |difference |
|----------|-------|------|---------|-----------|
|code      |536    |55.20 |NC       |NC         |
|docstring |16     |1.65  |NC       |NC         |
|comment   |206    |21.22 |NC       |NC         |
|empty     |213    |21.94 |NC       |NC         |

Duplication
-----------

|                         |now   |previous |difference |
|-------------------------|------|---------|-----------|
|nb duplicated lines      |0     |0        |0          |
|percent duplicated lines |0.000 |0.000    |=          |

Messages by category
--------------------

|type       |number |previous |difference |
|-----------|-------|---------|-----------|
|convention |82     |82       |82         |
|refactor   |5      |5        |5          |
|warning    |74     |74       |74         |
|error      |0      |0        |0          |

Messages
--------

| message id                     | occurrences |
|------------------------------- | ------------|
| unspecified-encoding           | 51          |
| missing-function-docstring     | 35          |
| trailing-whitespace            | 24          |
| line-too-long                  | 18          |
| redefined-outer-name           | 10          |
| f-string-without-interpolation | 8           |
| wrong-import-order             | 2           |
| consider-using-in              | 2           |
| broad-exception-caught         | 2           |
| unused-variable                | 1           |
| too-many-nested-blocks         | 1           |
| too-many-branches              | 1           |
| superfluous-parens             | 1           |
| subprocess-run-check           | 1           |
| missing-module-docstring       | 1           |
| invalid-name                   | 1           |
| consider-using-with            | 1           |
| bad-indentation                | 1           |

------------------------------------------------------------------
Your code has been rated at 6.92/10 (previous run: 6.92/10, +0.00)
</details>

### PR DESCRIPTION
**Pull request by Younis-Ahmed**
## Formatting PR Summary

This PR provides several fixes and improvements:

- **Fixes #8 and partially fixes #5**: Improved the formatting of the codebase to adhere to PEP8 standards. This includes changes such as fixing indentation, removing unnecessary whitespace, and improving the readability of the code.
- **Added error logs**: Introduced a new `errors_log` directory to track pylint linting reports. This will help us maintain a high-quality codebase and quickly identify any areas that need improvement. _added the directory and pylintrc to MANIFEST.in to exclude. upon compilation for pypi_
- **Fixes #7**: Removed the `betty_handler.py` module. The function inside this module was a duplication.
- **Pushing code rating**: The codebase overall quality has been enhanced from ~6± to ~9±.
------------
- **Note**:  Perfect code rating 10 was achieved by artificially utilizing ``pylint disabled`` for certain errors and can be found by parsing the codebase with `pylint` inside the package _For future contributions_.
----------
- **CI enhancements**: Added github action to run ``pylint && pycodestyle`` linter upon push or PR, Also added Python matrix  ``<-- [3.8, 3.9, 3.10]``

## Major changes Made

- Improved code formatting and readability.
- Added `errors_log`.
- Removed `betty_handler.py` module. 
- Code rating enhanced from ~6± to ~9±.
- Continuous integration for linting upon push and pull request.
-  Fixes #8 #7 and partially fixes #5

### CODE REVIEW

**Comment by be-great** [comment]
@Younis-Ahmed  can you document the commands you are using to run the test cases on the errors_log folder and the pylint. 
I really like this idea "Continuous integration for linting upon push and pull request." you really did a good job. 🙏

**Comment by Younis-Ahmed** [comment]
@be-great Thanks 🙏

Here you go!
```sh
pylint "$file" --reports=y -f parseable >> $outputfile
```
_**Please note that this is code snippet is part of a bash script i made to integrate into my workflow, it replaces the need to use ```pylint``` command directly. Instead, I use the script as it logs all attempts of invoking ``pylint``**_ 

The rationale behind this workflow is to log everything that happens within the linting scope, with the integration of my PR the github action will reject merging all code that is not conforming to PEP8 rules. Leaving holes in the project memory.

## CI workflow
```mermaid
stateDiagram-v2
   [*] --> NewPR
   NewPR --> linting_action: triggered
   linting_action --> isValid: pylint and pycodestyle validation
   isValid --> yes: Merge
   isValid --> no: exit 1
   no --> Terminated
   yes --> Terminated
   Terminated--> [*]
```
<br>

 #### If you want this level of logs records in your project let me know and i will add the script <-- This can be enforced at the `readme contribution section`

**Comment by be-great** [comment]
> Here you go!
> 
> ```shell
> pylint "$file" --reports=y -f parseable >> $outputfile
> ```

Okay, I will test it, and notify you.

**Review by Younis-Ahmed — COMMENTED** [review]
merged

**Pull request merged**
